language: ruby
sudo: false
addons:
  apt:
    packages:
    - bc
    - libc6:i386
    - libstdc++6:i386
    - zlib1g:i386
    - gcc-multilib
notifications:
  irc: "chat.freenode.net#buildroot"
env:
  matrix:
   - DEFCONFIG_NAME=acmesystems_aria_g25_128mb_defconfig
   - DEFCONFIG_NAME=acmesystems_aria_g25_256mb_defconfig
   - DEFCONFIG_NAME=acmesystems_arietta_g25_128mb_defconfig
   - DEFCONFIG_NAME=acmesystems_arietta_g25_256mb_defconfig
   - DEFCONFIG_NAME=altera_socdk_defconfig
   - DEFCONFIG_NAME=altera_sockit_defconfig
   - DEFCONFIG_NAME=armadeus_apf27_defconfig
   - DEFCONFIG_NAME=armadeus_apf28_defconfig
   - DEFCONFIG_NAME=armadeus_apf51_defconfig
   - DEFCONFIG_NAME=armadeus_apf9328_defconfig
   - DEFCONFIG_NAME=arm_foundationv8_defconfig
   - DEFCONFIG_NAME=arm_juno_defconfig
   - DEFCONFIG_NAME=at91sam9260eknf_defconfig
   - DEFCONFIG_NAME=at91sam9g20dfc_defconfig
   - DEFCONFIG_NAME=at91sam9g45m10ek_defconfig
   - DEFCONFIG_NAME=at91sam9rlek_defconfig
   - DEFCONFIG_NAME=at91sam9x5ek_defconfig
   - DEFCONFIG_NAME=atmel_sama5d2_xplained_mmc_defconfig
   - DEFCONFIG_NAME=atmel_sama5d3xek_defconfig
   - DEFCONFIG_NAME=atmel_sama5d3_xplained_defconfig
   - DEFCONFIG_NAME=atmel_sama5d3_xplained_mmc_defconfig
   - DEFCONFIG_NAME=atmel_sama5d4ek_defconfig
   - DEFCONFIG_NAME=atmel_sama5d4_xplained_defconfig
   - DEFCONFIG_NAME=atmel_sama5d4_xplained_mmc_defconfig
   - DEFCONFIG_NAME=beaglebone_defconfig
   - DEFCONFIG_NAME=calao_qil_a9260_defconfig
   - DEFCONFIG_NAME=calao_tny_a9g20_lpw_defconfig
   - DEFCONFIG_NAME=calao_usb_a9260_defconfig
   - DEFCONFIG_NAME=calao_usb_a9263_defconfig
   - DEFCONFIG_NAME=calao_usb_a9g20_lpw_defconfig
   - DEFCONFIG_NAME=ci20_defconfig
   - DEFCONFIG_NAME=cubieboard2_defconfig
   - DEFCONFIG_NAME=cubieboard_defconfig
   - DEFCONFIG_NAME=firefly_rk3288_defconfig
   - DEFCONFIG_NAME=firefly_rk3288_demo_defconfig
   - DEFCONFIG_NAME=freescale_imx28evk_defconfig
   - DEFCONFIG_NAME=freescale_imx31_3stack_defconfig
   - DEFCONFIG_NAME=freescale_imx6dlsabreauto_defconfig
   - DEFCONFIG_NAME=freescale_imx6dlsabresd_defconfig
   - DEFCONFIG_NAME=freescale_imx6qsabreauto_defconfig
   - DEFCONFIG_NAME=freescale_imx6qsabresd_defconfig
   - DEFCONFIG_NAME=freescale_imx6sololiteevk_defconfig
   - DEFCONFIG_NAME=freescale_imx6sxsabresd_defconfig
   - DEFCONFIG_NAME=freescale_imx6ulevk_defconfig
   - DEFCONFIG_NAME=freescale_mpc8315erdb_defconfig
   - DEFCONFIG_NAME=freescale_p1010rdb_pa_defconfig
   - DEFCONFIG_NAME=freescale_p2020ds_defconfig
   - DEFCONFIG_NAME=galileo_defconfig
   - DEFCONFIG_NAME=kb9202_defconfig
   - DEFCONFIG_NAME=lego_ev3_defconfig
   - DEFCONFIG_NAME=mini2440_defconfig
   - DEFCONFIG_NAME=minnowboard_defconfig
   - DEFCONFIG_NAME=minnowboard_max_defconfig
   - DEFCONFIG_NAME=minnowboard_max-graphical_defconfig
   - DEFCONFIG_NAME=mx53loco_defconfig
   - DEFCONFIG_NAME=nitrogen6sx_defconfig
   - DEFCONFIG_NAME=nitrogen6x_defconfig
   - DEFCONFIG_NAME=nitrogen7_defconfig
   - DEFCONFIG_NAME=odroidc2_defconfig
   - DEFCONFIG_NAME=olimex_a20_olinuxino_lime2_defconfig
   - DEFCONFIG_NAME=olimex_a20_olinuxino_lime_defconfig
   - DEFCONFIG_NAME=olimex_a20_olinuxino_lime_mali_defconfig
   - DEFCONFIG_NAME=olimex_a20_olinuxino_micro_defconfig
   - DEFCONFIG_NAME=olimex_imx233_olinuxino_defconfig
   - DEFCONFIG_NAME=openblocks_a6_defconfig
   - DEFCONFIG_NAME=orangepipc_defconfig
   - DEFCONFIG_NAME=pandaboard_defconfig
   - DEFCONFIG_NAME=qemu_aarch64_virt_defconfig
   - DEFCONFIG_NAME=qemu_arm_versatile_defconfig
   - DEFCONFIG_NAME=qemu_arm_vexpress_defconfig
   - DEFCONFIG_NAME=qemu_m68k_mcf5208_defconfig
   - DEFCONFIG_NAME=qemu_m68k_q800_defconfig
   - DEFCONFIG_NAME=qemu_microblazebe_mmu_defconfig
   - DEFCONFIG_NAME=qemu_microblazeel_mmu_defconfig
   - DEFCONFIG_NAME=qemu_mips64el_malta_defconfig
   - DEFCONFIG_NAME=qemu_mips64_malta_defconfig
   - DEFCONFIG_NAME=qemu_mipsel_malta_defconfig
   - DEFCONFIG_NAME=qemu_mips_malta_defconfig
   - DEFCONFIG_NAME=qemu_ppc64_pseries_defconfig
   - DEFCONFIG_NAME=qemu_ppc_g3beige_defconfig
   - DEFCONFIG_NAME=qemu_ppc_mpc8544ds_defconfig
   - DEFCONFIG_NAME=qemu_ppc_virtex_ml507_defconfig
   - DEFCONFIG_NAME=qemu_sh4eb_r2d_defconfig
   - DEFCONFIG_NAME=qemu_sh4_r2d_defconfig
   - DEFCONFIG_NAME=qemu_sparc64_sun4u_defconfig
   - DEFCONFIG_NAME=qemu_sparc_ss10_defconfig
   - DEFCONFIG_NAME=qemu_x86_64_defconfig
   - DEFCONFIG_NAME=qemu_x86_defconfig
   - DEFCONFIG_NAME=qemu_xtensa_lx60_defconfig
   - DEFCONFIG_NAME=qemu_xtensa_lx60_nommu_defconfig
   - DEFCONFIG_NAME=qmx6_defconfig
   - DEFCONFIG_NAME=raspberrypi2_defconfig
   - DEFCONFIG_NAME=raspberrypi3_defconfig
   - DEFCONFIG_NAME=raspberrypi_defconfig
   - DEFCONFIG_NAME=riotboard_defconfig
   - DEFCONFIG_NAME=s6lx9_microboard_defconfig
   - DEFCONFIG_NAME=sheevaplug_defconfig
   - DEFCONFIG_NAME=snps_aarch64_vdk_defconfig
   - DEFCONFIG_NAME=snps_axs101_defconfig
   - DEFCONFIG_NAME=snps_axs103_defconfig
   - DEFCONFIG_NAME=snps_hs38_smp_vdk_defconfig
   - DEFCONFIG_NAME=snps_hs38_vdk_defconfig
   - DEFCONFIG_NAME=stm32f429_disco_defconfig
   - DEFCONFIG_NAME=stm32f469_disco_defconfig
   - DEFCONFIG_NAME=telit_evk_pro3_defconfig
   - DEFCONFIG_NAME=ts5x00_defconfig
   - DEFCONFIG_NAME=udoo_quad_defconfig
   - DEFCONFIG_NAME=via_imx6_vab820_defconfig
   - DEFCONFIG_NAME=wandboard_defconfig
   - DEFCONFIG_NAME=warpboard_defconfig
   - DEFCONFIG_NAME=zynq_microzed_defconfig
   - DEFCONFIG_NAME=zynq_zc706_defconfig
   - DEFCONFIG_NAME=zynq_zed_defconfig
script:
- echo 'Clone Buildroot repository'
- git clone git://git.busybox.net/buildroot
- cd buildroot
- git checkout 63cd7b84a331dcba7c53a375cc33f53b6b48474a
# Crude hack to account for the fact that XFS is used by Travis, and
# consumes less blocks than ext2/3/4, and therefore defeats mke2img
# calculation. Without this, the altera_*_defconfig fail to build.
- sed -i 's/1300/2500/' package/mke2img/mke2img
- echo 'Configure Buildroot'
- make ${DEFCONFIG_NAME}
- while true ; do echo "Still building" ; sleep 60 ; done &
- stupidpid=$!
- echo 'Build buildroot'
- make > >(tee build.log |grep '>>>') 2>&1
- kill ${stupidpid}
- echo 'Display end of log'
- tail -1000 build.log
- echo 'Upload log file'
- scp -oStrictHostKeyChecking=no -i ${HOME}/.ssh/buildroot-kim build.log buildroot@autobuild.buildroot.org:~/defconfigs-build/${TRAVIS_BUILD_NUMBER}-${DEFCONFIG_NAME}-${TRAVIS_JOB_ID}.log
before_install:
- mkdir -p ${HOME}/.ssh/
- openssl aes-256-cbc -K $encrypted_ff43b1ef5e6e_key -iv $encrypted_ff43b1ef5e6e_iv -in buildroot-kim-ssh-key -out ${HOME}/.ssh/buildroot-kim -d
- md5sum ${HOME}/.ssh/buildroot-kim
- chmod 600 ${HOME}/.ssh/buildroot-kim
